version: "3.8"

services:
  mysql:
  glpi:
    image: fametec/glpi:latest
    restart: unless-stopped
    volumes:
      - glpi-volume-files:/var/www/html/files:rw
      - glpi-volume-plugins:/var/www/html/plugins:rw
    environment:
      GLPI_LANG: pt_BR
      MARIADB_HOST: mariadb-glpi
      MARIADB_PORT: 3306
      MARIADB_DATABASE: glpi
      MARIADB_USER: glpi-user
      MARIADB_PASSWORD: glpi-pass
      VERSION: "9.5.6"
      PLUGINS: "all"
