version: "3.3"
services:
  mysql-glpi:
    image: kirilyaksa/glpi-docker/mysql
    restart: unless-stopped
    volumes:
      - mysql-glpi-volume:/var/lib/mysql:rw
    environment:
      MYSQL_DATABASE: glpi
      MYSQL_USER: sergey
      MYSQL_PASSWORD: genius123
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    ports:
      - 3306:3306
    networks:
      - glpi-backend
  #
  #
  glpi:
    image: irilyaksa/glpi-docker/glpi:9.5.6
    restart: unless-stopped
    volumes:
      - glpi-volume-files:/var/www/html/files:rw
      - glpi-volume-plugins:/var/www/html/plugins:rw
      - glpi-volume-config:/var/www/html/config:rw
    environment:
      GLPI_LANG: uk_UA
      MYSQL_HOST: mariadb-glpi
      MYSQL_PORT: 3306
      MYSQL_DATABASE: glpi
      MYSQL_USER: sergey
      MYSQL_PASSWORD: genius123
      VERSION: "9.5.6"
      PLUGINS: "all"
    depends_on:
      - mysql-glpi
    ports:
      - 80:80
    networks:
      - glpi-frontend
      - glpi-backend
  #
  # CRON
  #
  crond:
    image: fametec/glpi:9.5.6-crond
    restart: unless-stopped
    depends_on:
      - mariadb-glpi
    environment:
      MARIADB_HOST: mariadb-glpi
      MARIADB_PORT: 3306
      MARIADB_DATABASE: glpi
      MARIADB_USER: glpi-user
      MARIADB_PASSWORD: glpi-pass
    volumes:
      - glpi-volume-files:/var/www/html/files:rw
      - glpi-volume-plugins:/var/www/html/plugins:rw
      - glpi-volume-config:/var/www/html/config:rw
    networks:
      - glpi-backend
#
# VOLUMES
#
volumes:
  glpi-volume-files:
  glpi-volume-plugins:
  glpi-volume-config:
  mariadb-glpi-volume:
    #
    # NETWORKS
    #
networks:
  glpi-frontend:
  glpi-backend:
