FROM ubuntu:22
# Adding build tools to make yarn install work on Apple silicon / arm64 machines
#Задаем переменные среды
ENV VERSION 9.5.6
ENV GLPI_LANG uk_UA
#ENV GLPI_LANG ru_RU
ENV MYSQL_HOST mysql-glpi
ENV MYSQL_PORT 3306
ENV MYSQL_DATABASE glpi
ENV MYSQL_USER sergey
ENV MYSQL_PASSWORD genius123
#задаем рабочую директорию сайта 
WORKDIR /var/www/html
#так как glpi версии 9.5.6 для него необходим php 8.0, поетому устанавливаем репозиторий и обновлям пакеты
RUN apt -y install software-properties-common && add-apt-repository ppa:ondrej/php && apt update
RUN  apt -y install \
    php8.0 \
    php8.0-common \
    php8.0-mcrypt \
    php8.0-cli \
    php8.0-gd \
    php8.0-mysqli \
    php8.0-mbstring \
    php8.0-mysqli \
    php8.0-curl \
    php8.0-imap \
    php8.0-ldap \
    php8.0-opcache \
    php8.0-apcu \
    php8.0-xmlrpc \
    php8.0-intl \    
    php8.0-zip \
    php8.0-simplexml \
    php8.0-bz2 \
    net-tools
# перемещаем файлы конфигурации
ADD php_conf /etc/php/8.0/apache2/conf.d/
ADD apache_conf /etc/apache2/conf-enabled/
# задаем имена для сервера
RUN echo "ServerName GLPI" > /etc/apache2/conf-enabled/servername.conf && hostname GLPI

RUN wget -P /tmp/ https://github.com/glpi-project/glpi/releases/download/9.5.6/glpi-9.5.6.tgz \
    && tar -zxf /tmp/glpi-9.5.6.tgz -C /tmp/ \
    && mv -f /tmp/glpi/* /var/www/html/ \
    && chown -R www-data:www-data /var/www/html \
    && rm -rf /tmp/glpi-9.5.6.tgz

VOLUME [ "/var/www/html/files", "/var/www/html/plugins" ]

ADD scripts/glpi-entrypoint.sh scripts/plugins.sh /

RUN chmod 755 /glpi-entrypoint.sh /plugins.sh 

EXPOSE 80/tcp 

CMD ["/glpi-entrypoint.sh"]